const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const assert = require('node:assert/strict');

const root = path.join(__dirname, '..', '..');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const serverSource = fs.readFileSync(path.join(root, 'server.js'), 'utf8');

test('browser vendor packages are build-only dependencies', () => {
  for (const dependency of ['@xterm/addon-fit', '@xterm/xterm', 'dompurify', 'lucide']) {
    assert.equal(manifest.dependencies?.[dependency], undefined, `${dependency} must not enter the production install`);
    assert.equal(typeof manifest.devDependencies?.[dependency], 'string', `${dependency} is still required to build the client`);
  }
});

test('the client build emits only the browser vendor files the server exposes', () => {
  for (const file of ['xterm.js', 'xterm.css', 'xterm-fit.js', 'lucide.js']) {
    const built = path.join(root, 'assets', 'vendor', file);
    assert.ok(fs.statSync(built).size > 0, `${file} must be generated by build:client`);
    assert.match(serverSource, new RegExp(`assets/vendor/${file.replace('.', '\\.')}`));
  }
  assert.doesNotMatch(serverSource, /['"]node_modules\/(?:@xterm|lucide)/);
});
